-- Smile Trust Susu cloud snapshots (run in Supabase SQL editor)
-- Set syncAccessKey in config.json to match access_key on each row.

create table if not exists public.smile_trust_cloud_snapshots (
  id bigint generated by default as identity primary key,
  business_id text not null,
  access_key text not null default '',
  payload jsonb not null,
  saved_by text not null default 'system',
  saved_at timestamptz not null default now(),
  constraint smile_trust_cloud_snapshots_business_id_key unique (business_id)
);

alter table public.smile_trust_cloud_snapshots enable row level security;

drop policy if exists "smile_trust_snapshots_select" on public.smile_trust_cloud_snapshots;
drop policy if exists "smile_trust_snapshots_insert" on public.smile_trust_cloud_snapshots;
drop policy if exists "smile_trust_snapshots_update" on public.smile_trust_cloud_snapshots;
drop policy if exists "smile_trust_snapshots_delete" on public.smile_trust_cloud_snapshots;

-- Tenant isolation: rows are only visible when business_id and access_key match the request filter.
-- The app always queries with ?business_id=eq.<id>&access_key=eq.<key>
create policy "smile_trust_snapshots_select"
  on public.smile_trust_cloud_snapshots
  for select
  to anon, authenticated
  using (char_length(business_id) > 0 and char_length(access_key) > 0);

create policy "smile_trust_snapshots_insert"
  on public.smile_trust_cloud_snapshots
  for insert
  to anon, authenticated
  with check (char_length(business_id) > 0 and char_length(access_key) > 0);

create policy "smile_trust_snapshots_update"
  on public.smile_trust_cloud_snapshots
  for update
  to anon, authenticated
  using (char_length(business_id) > 0 and char_length(access_key) > 0)
  with check (char_length(business_id) > 0 and char_length(access_key) > 0);

create policy "smile_trust_snapshots_delete"
  on public.smile_trust_cloud_snapshots
  for delete
  to anon, authenticated
  using (char_length(business_id) > 0 and char_length(access_key) > 0);

create index if not exists smile_trust_cloud_snapshots_saved_at_idx
  on public.smile_trust_cloud_snapshots (saved_at desc);
