-- Smile Trust Susu cloud snapshots (run in Supabase SQL editor, then apply migrations).
-- Access requires a staff session issued by the staff-login Edge Function: its JWT carries a
-- server-set app_metadata.business_code that must match the row. The public anon key alone
-- grants nothing. access_key is a legacy column kept only for existing rows.

create table if not exists public.smile_trust_cloud_snapshots (
  id bigint generated by default as identity primary key,
  business_id text not null,
  access_key text default '',
  payload jsonb not null,
  saved_by text not null default 'system',
  saved_at timestamptz not null default now(),
  constraint smile_trust_cloud_snapshots_business_id_key unique (business_id)
);

alter table public.smile_trust_cloud_snapshots enable row level security;

drop policy if exists "smile_trust_snapshots_select" on public.smile_trust_cloud_snapshots;
drop policy if exists "smile_trust_snapshots_insert" on public.smile_trust_cloud_snapshots;
drop policy if exists "smile_trust_snapshots_update" on public.smile_trust_cloud_snapshots;
drop policy if exists "smile_trust_snapshots_delete" on public.smile_trust_cloud_snapshots;
drop policy if exists st_snapshots_select on public.smile_trust_cloud_snapshots;
drop policy if exists st_snapshots_insert on public.smile_trust_cloud_snapshots;
drop policy if exists st_snapshots_update on public.smile_trust_cloud_snapshots;

revoke all on public.smile_trust_cloud_snapshots from anon;
revoke delete, truncate on public.smile_trust_cloud_snapshots from authenticated;
grant select, insert, update on public.smile_trust_cloud_snapshots to authenticated;

create policy st_snapshots_select
  on public.smile_trust_cloud_snapshots
  for select to authenticated
  using (business_id = nullif(auth.jwt() -> 'app_metadata' ->> 'business_code', ''));

create policy st_snapshots_insert
  on public.smile_trust_cloud_snapshots
  for insert to authenticated
  with check (business_id = nullif(auth.jwt() -> 'app_metadata' ->> 'business_code', ''));

create policy st_snapshots_update
  on public.smile_trust_cloud_snapshots
  for update to authenticated
  using (business_id = nullif(auth.jwt() -> 'app_metadata' ->> 'business_code', ''))
  with check (business_id = nullif(auth.jwt() -> 'app_metadata' ->> 'business_code', ''));

create index if not exists smile_trust_cloud_snapshots_saved_at_idx
  on public.smile_trust_cloud_snapshots (saved_at desc);
